import { environment } from '../config/environment.js';

type HttpMethod = 'get' | 'post' | 'put' | 'patch' | 'delete';
interface DocumentedRoute {
  readonly method: HttpMethod;
  readonly path: string;
  readonly summary: string;
  readonly tag: string;
  readonly secured?: boolean;
  readonly requestExample?: Readonly<Record<string, unknown>>;
}

const routes: readonly DocumentedRoute[] = [
  {
    method: 'get',
    path: '/api/v1/audit',
    summary: 'List tenant-scoped immutable audit records without sensitive network values',
    tag: 'Audit',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/notifications/events/preferences',
    summary: 'Get the signed-in user event-notification channel and category preferences',
    tag: 'Event notifications',
    secured: true,
  },
  {
    method: 'put',
    path: '/api/v1/notifications/events/preferences',
    summary: 'Update optional event-notification channels while preserving mandatory notices',
    tag: 'Event notifications',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/history',
    summary: 'List the signed-in user event participation record with academic-period filters',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}/participants',
    summary: 'Search and drill into the tenant-scoped event participant register',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}/analytics',
    summary: 'Get role-scoped event attendance analytics with optional date range',
    tag: 'Event analytics',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}/analytics/export/{format}',
    summary: 'Export event analytics as CSV, Excel, or PDF',
    tag: 'Event analytics',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/uploads/configuration',
    summary: 'Get authenticated secure-media availability and limits',
    tag: 'Media uploads',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/uploads',
    summary: 'Validate and upload an announcement or event file to tenant-scoped storage',
    tag: 'Media uploads',
    secured: true,
  },
  { method: 'get', path: '/api/v1/health', summary: 'Get service health', tag: 'Operations' },
  {
    method: 'get',
    path: '/api/v1/country',
    summary: 'Resolve privacy-conscious country copy',
    tag: 'Public',
  },
  { method: 'get', path: '/api/v1/health/live', summary: 'Get liveness status', tag: 'Operations' },
  {
    method: 'get',
    path: '/api/v1/health/ready',
    summary: 'Get database readiness status',
    tag: 'Operations',
  },
  {
    method: 'post',
    path: '/api/v1/auth/register',
    summary: 'Register a university account',
    tag: 'Authentication',
    requestExample: {
      universityId: 'lagos-metropolitan-university',
      firstName: 'Ada',
      lastName: 'Okafor',
      email: 'ada.okafor@university.edu.ng',
      password: 'SecurePassphrase2026!',
    },
  },
  {
    method: 'post',
    path: '/api/v1/auth/login',
    summary: 'Sign in and create a rotating session',
    tag: 'Authentication',
    requestExample: {
      universityId: 'lagos-metropolitan-university',
      email: 'ada.okafor@university.edu.ng',
      password: 'SecurePassphrase2026!',
    },
  },
  {
    method: 'post',
    path: '/api/v1/auth/verify-email',
    summary: 'Verify a registered email address',
    tag: 'Authentication',
    requestExample: { token: 'single-use-email-verification-token' },
  },
  {
    method: 'post',
    path: '/api/v1/auth/resend-verification',
    summary: 'Request a replacement verification email',
    tag: 'Authentication',
    requestExample: {
      universityId: 'lagos-metropolitan-university',
      email: 'ada.okafor@university.edu.ng',
    },
  },
  {
    method: 'post',
    path: '/api/v1/auth/forgot-password',
    summary: 'Request password reset instructions',
    tag: 'Authentication',
    requestExample: {
      universityId: 'lagos-metropolitan-university',
      email: 'ada.okafor@university.edu.ng',
    },
  },
  {
    method: 'post',
    path: '/api/v1/auth/reset-password',
    summary: 'Reset a password using a single-use token',
    tag: 'Authentication',
    requestExample: { token: 'single-use-password-reset-token', password: 'NewSecurePass2026!' },
  },
  {
    method: 'post',
    path: '/api/v1/auth/refresh',
    summary: 'Rotate the refresh token and access token',
    tag: 'Authentication',
  },
  {
    method: 'post',
    path: '/api/v1/auth/logout',
    summary: 'Revoke the active refresh token',
    tag: 'Authentication',
  },
  {
    method: 'get',
    path: '/api/v1/auth/sessions',
    summary: 'List active device sessions',
    tag: 'Authentication',
    secured: true,
  },
  {
    method: 'delete',
    path: '/api/v1/auth/sessions/{sessionId}',
    summary: 'Revoke an active device session',
    tag: 'Authentication',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/auth/logout-all',
    summary: 'Revoke every device session',
    tag: 'Authentication',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/auth/change-password',
    summary: 'Change the signed-in user password',
    tag: 'Authentication',
    secured: true,
    requestExample: {
      currentPassword: 'CurrentSecurePass2026!',
      newPassword: 'NewSecurePass2026!',
    },
  },
  {
    method: 'post',
    path: '/api/v1/contact',
    summary: 'Submit an institutional demonstration request',
    tag: 'Public',
    requestExample: {
      universityName: 'Lagos Metropolitan University',
      contactName: 'Ada Okafor',
      email: 'ada.okafor@university.edu.ng',
      message: 'We would like to evaluate Attendity for our faculties and examination office.',
    },
  },
  {
    method: 'get',
    path: '/api/v1/portal/summary',
    summary: 'Get the role-scoped portal summary',
    tag: 'Portal',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/academic/structure',
    summary:
      'List paginated institution campuses, faculties, programmes, levels, periods, and venues',
    tag: 'Academic structure',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/academic/structure',
    summary: 'Create a tenant-scoped academic structure record',
    tag: 'Academic structure',
    secured: true,
    requestExample: { kind: 'campus', code: 'MAIN', name: 'Main Campus', status: 'active' },
  },
  {
    method: 'patch',
    path: '/api/v1/academic/structure/{structureId}',
    summary: 'Update an academic structure record and its hierarchy',
    tag: 'Academic structure',
    secured: true,
    requestExample: { name: 'Main Academic Campus', isCurrent: false },
  },
  {
    method: 'delete',
    path: '/api/v1/academic/structure/{structureId}',
    summary: 'Deactivate an academic structure record while preserving history',
    tag: 'Academic structure',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/academic/departments',
    summary: 'List university departments',
    tag: 'Academic',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/academic/departments',
    summary: 'Create a department',
    tag: 'Academic',
    secured: true,
    requestExample: { code: 'CSC', name: 'Computer Science', facultyName: 'Faculty of Science' },
  },
  {
    method: 'get',
    path: '/api/v1/academic/courses',
    summary: 'List courses',
    tag: 'Academic',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/academic/courses',
    summary: 'Create a course',
    tag: 'Academic',
    secured: true,
    requestExample: {
      code: 'CSC 401',
      title: 'Software Engineering',
      creditUnits: 3,
      departmentId: '6650f27f52cf1956c94d0110',
      attendanceRequirement: 75,
    },
  },
  {
    method: 'patch',
    path: '/api/v1/academic/courses/{courseId}/lecturer',
    summary: 'Assign a lecturer to a course',
    tag: 'Academic',
    secured: true,
    requestExample: { lecturerId: '6650f27f52cf1956c94d0120' },
  },
  {
    method: 'get',
    path: '/api/v1/academic/schedules',
    summary: 'List role-scoped class schedules',
    tag: 'Class schedules',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/academic/schedules',
    summary: 'Create a class schedule and reconcile reminders',
    tag: 'Class schedules',
    secured: true,
    requestExample: {
      courseId: '6650f27f52cf1956c94d0111',
      startsAt: '2026-08-05T09:00:00.000Z',
      endsAt: '2026-08-05T10:30:00.000Z',
      venue: 'Academic Block A101',
      timeZone: 'Africa/Lagos',
    },
  },
  {
    method: 'patch',
    path: '/api/v1/academic/schedules/{scheduleId}',
    summary: 'Update an upcoming class and reschedule reminders',
    tag: 'Class schedules',
    secured: true,
    requestExample: { startsAt: '2026-08-05T10:00:00.000Z', venue: 'Innovation Hub 2' },
  },
  {
    method: 'post',
    path: '/api/v1/academic/schedules/{scheduleId}/cancel',
    summary: 'Cancel a class and its pending reminders',
    tag: 'Class schedules',
    secured: true,
    requestExample: { reason: 'The faculty building is unavailable.' },
  },
  {
    method: 'get',
    path: '/api/v1/users',
    summary: 'List tenant users',
    tag: 'Users',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/users/{userId}/status',
    summary: 'Update an account status',
    tag: 'Users',
    secured: true,
    requestExample: { accountStatus: 'active' },
  },
  {
    method: 'get',
    path: '/api/v1/registrations/mine',
    summary: 'List the signed-in student registrations',
    tag: 'Registrations',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/registrations',
    summary: 'List course registrations',
    tag: 'Registrations',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/registrations',
    summary: 'Create a course registration',
    tag: 'Registrations',
    secured: true,
    requestExample: {
      studentId: '6650f27f52cf1956c94d0130',
      courseId: '6650f27f52cf1956c94d0140',
      registrationNumber: '2026/CSC/001',
    },
  },
  {
    method: 'patch',
    path: '/api/v1/registrations/{registrationId}',
    summary: 'Update a registration status',
    tag: 'Registrations',
    secured: true,
    requestExample: { status: 'approved' },
  },
  {
    method: 'get',
    path: '/api/v1/attendance/lecturer',
    summary: 'Get the lecturer attendance workspace',
    tag: 'Attendance',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/attendance/sessions',
    summary: 'Open an attendance session',
    tag: 'Attendance',
    secured: true,
    requestExample: {
      courseId: '6650f27f52cf1956c94d0140',
      durationMinutes: 60,
      qrMode: 'static',
      qrRotationSeconds: 60,
      gpsRequired: true,
      faceVerificationRequired: false,
      latitude: 6.5244,
      longitude: 3.3792,
      maximumRadiusMetres: 100,
    },
  },
  {
    method: 'get',
    path: '/api/v1/attendance/sessions/{sessionId}/qr.pdf',
    summary: 'Download a lecturer-owned static attendance QR PDF',
    tag: 'Attendance',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/attendance/sessions/{sessionId}/close',
    summary: 'Close an attendance session',
    tag: 'Attendance',
    secured: true,
    requestExample: { reason: 'Lecture completed' },
  },
  {
    method: 'get',
    path: '/api/v1/attendance/student',
    summary: 'Get the student attendance workspace',
    tag: 'Attendance',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/attendance/check-in/requirements',
    summary: 'Resolve check-in verification requirements',
    tag: 'Attendance',
    secured: true,
    requestExample: { credential: 'ATTENDITY-SESSION-CREDENTIAL' },
  },
  {
    method: 'post',
    path: '/api/v1/attendance/check-in',
    summary: 'Mark attendance using a live credential',
    tag: 'Attendance',
    secured: true,
    requestExample: {
      credential: 'ATTENDITY-SESSION-CREDENTIAL',
      latitude: 6.5244,
      longitude: 3.3792,
    },
  },
  {
    method: 'post',
    path: '/api/v1/attendance/face-profile',
    summary: 'Enrol a student face profile',
    tag: 'Attendance',
    secured: true,
    requestExample: { image: 'data:image/jpeg;base64,...' },
  },
  {
    method: 'get',
    path: '/api/v1/attendance/clearance/{registrationNumber}',
    summary: 'Verify legacy registration clearance',
    tag: 'Attendance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/settings/institution',
    summary: 'Get safe institution display configuration',
    tag: 'Settings',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/settings',
    summary: 'Get institution settings',
    tag: 'Settings',
    secured: true,
  },
  {
    method: 'put',
    path: '/api/v1/settings',
    summary: 'Update institution settings',
    tag: 'Settings',
    secured: true,
    requestExample: {
      institutionName: 'Lagos Metropolitan University',
      institutionType: 'university',
      countryCode: 'NG',
      countryName: 'Nigeria',
      primaryColor: '#14532D',
      secondaryColor: '#B8892D',
      terminologyPreset: 'university',
      terminologyOverrides: {},
      staffTitlePreference: 'Lecturer',
      studentIdentifierLabel: 'Matriculation number',
      timeZone: 'Africa/Lagos',
      dateFormat: 'DD/MM/YYYY',
      academicSession: '2026/2027',
      currentSemester: 'First Semester',
      attendanceRequirement: 75,
      qrRotationSeconds: 60,
      gpsRadiusMetres: 100,
      lateArrivalMinutes: 15,
    },
  },
  {
    method: 'get',
    path: '/api/v1/analytics/overview',
    summary: 'Get role-scoped analytics',
    tag: 'Analytics',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/analytics/my-risk',
    summary: 'Get student attendance risks',
    tag: 'Analytics',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/analytics/reports',
    summary: 'Generate an analytics report',
    tag: 'Analytics',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/notifications',
    summary: 'List notifications',
    tag: 'Notifications',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/notifications/reminders/preferences',
    summary: 'Get private class reminder preferences and channel availability',
    tag: 'Class reminders',
    secured: true,
  },
  {
    method: 'put',
    path: '/api/v1/notifications/reminders/preferences',
    summary: 'Update class reminder defaults and per-class overrides',
    tag: 'Class reminders',
    secured: true,
    requestExample: {
      enabled: true,
      defaultOffsetMinutes: 30,
      channels: ['in_app', 'email'],
      preferredTimeZone: 'Africa/Lagos',
      quietHours: { enabled: true, startMinute: 1320, endMinute: 420 },
      mutedCourseIds: [],
      overrides: [],
    },
  },
  {
    method: 'post',
    path: '/api/v1/notifications/reminders/preferences/reset',
    summary: 'Restore class reminder defaults',
    tag: 'Class reminders',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/notifications/reminders/history',
    summary: 'List the signed-in user private reminder delivery history',
    tag: 'Class reminders',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/notifications/reminders/test/{channel}',
    summary: 'Send a reminder channel test',
    tag: 'Class reminders',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/notifications/push/subscriptions',
    summary: 'Register a private browser push subscription',
    tag: 'Class reminders',
    secured: true,
  },
  {
    method: 'delete',
    path: '/api/v1/notifications/push/subscriptions',
    summary: 'Revoke a browser push subscription',
    tag: 'Class reminders',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/notifications/read-all',
    summary: 'Mark all notifications as read',
    tag: 'Notifications',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/notifications/{notificationId}/read',
    summary: 'Mark a notification as read',
    tag: 'Notifications',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/notifications/{notificationId}/archive',
    summary: 'Archive a notification',
    tag: 'Notifications',
    secured: true,
  },
  {
    method: 'delete',
    path: '/api/v1/notifications/{notificationId}',
    summary: 'Delete a notification',
    tag: 'Notifications',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/announcements',
    summary: 'List announcements targeted to the signed-in user',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/announcements/manage',
    summary: 'List announcements within the publisher scope',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/announcements',
    summary: 'Create a tenant-scoped announcement draft',
    tag: 'Announcements',
    secured: true,
    requestExample: {
      title: 'Examination briefing',
      message: 'Final-year students should attend the examination briefing.',
      category: 'academic',
      priority: 'high',
      audience: { roles: ['student'], level: '400 Level' },
      attachments: [],
      pinned: true,
      acknowledgementRequired: true,
      channels: ['in_app'],
    },
  },
  {
    method: 'get',
    path: '/api/v1/announcements/{announcementId}',
    summary: 'Get an authorized announcement detail',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/announcements/{announcementId}',
    summary: 'Edit a draft or scheduled announcement',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/announcements/{announcementId}/schedule',
    summary: 'Schedule an announcement publication',
    tag: 'Announcements',
    secured: true,
    requestExample: { publishAt: '2026-08-05T09:00:00.000Z' },
  },
  {
    method: 'post',
    path: '/api/v1/announcements/{announcementId}/publish',
    summary: 'Publish an announcement immediately',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/announcements/{announcementId}/archive',
    summary: 'Archive a published announcement',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/announcements/{announcementId}/cancel',
    summary: 'Cancel a draft or scheduled announcement',
    tag: 'Announcements',
    secured: true,
    requestExample: { reason: 'The briefing date is being reviewed.' },
  },
  {
    method: 'patch',
    path: '/api/v1/announcements/{announcementId}/pin',
    summary: 'Pin or unpin a published announcement',
    tag: 'Announcements',
    secured: true,
    requestExample: { pinned: true },
  },
  {
    method: 'get',
    path: '/api/v1/announcements/{announcementId}/delivery',
    summary: 'Get role-scoped announcement delivery totals',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/announcements/{announcementId}/read',
    summary: 'Mark a targeted announcement as read',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/announcements/{announcementId}/acknowledge',
    summary: 'Acknowledge a targeted announcement',
    tag: 'Announcements',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events',
    summary: 'List events assigned to the signed-in user',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/manage',
    summary: 'List events within the organizer scope',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/history',
    summary: 'Get personal event participation history',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events',
    summary: 'Create a tenant-scoped event draft',
    tag: 'Events',
    secured: true,
    requestExample: {
      title: 'Academic Success Orientation',
      description: 'Mandatory orientation for new students.',
      eventType: 'orientation',
      venue: 'Multipurpose Hall',
      startsAt: '2026-08-10T09:00:00.000Z',
      endsAt: '2026-08-10T11:00:00.000Z',
      timeZone: 'Africa/Lagos',
      mandatory: true,
      registrationRequired: false,
      audience: { roles: ['student'] },
      reminderOffsetsMinutes: [1440, 60],
      notificationChannels: ['in_app'],
      attendanceMethods: ['dynamic_qr', 'manual'],
      qrRotationSeconds: 60,
      faceVerificationRequired: false,
      manualAttendanceAllowed: true,
      pinAttendanceAllowed: false,
      attachments: [],
    },
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}',
    summary: 'Get an authorized event detail',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/events/{eventId}',
    summary: 'Edit a draft or scheduled event',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/publish',
    summary: 'Publish an event and materialize its audience',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/register',
    summary: 'Register for an assigned event',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/cancel',
    summary: 'Cancel an event and notify participants',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/archive',
    summary: 'Archive a completed or cancelled event',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/attendance/open',
    summary: 'Open event attendance using configured verification methods',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/events/{eventId}/attendance/{sessionId}/close',
    summary: 'Close an event attendance session',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/attendance/requirements',
    summary: 'Resolve event attendance verification requirements',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/attendance/check-in',
    summary: 'Record verified event attendance',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/attendance/manual',
    summary: 'Record authorized manual event attendance',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/events/{eventId}/participants/{userId}/excuse',
    summary: 'Approve an excused event absence',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}/analytics',
    summary: 'Get role-scoped event attendance analytics',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}/participants',
    summary: 'List searchable, paginated event participants within organizer scope',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/events/{eventId}/analytics/export/{format}',
    summary: 'Export event analytics as CSV, Excel, or PDF',
    tag: 'Events',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/verification/{reference}',
    summary: 'Publicly verify a signed clearance report',
    tag: 'Clearance',
  },
  {
    method: 'get',
    path: '/api/v1/clearance/eligibility',
    summary: 'Calculate live course eligibility',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/examiner/search',
    summary: 'Search clearance records as an examiner',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'post',
    path: '/api/v1/clearance/reports',
    summary: 'Generate a signed clearance report',
    tag: 'Clearance',
    secured: true,
    requestExample: { registrationId: '6650f27f52cf1956c94d0150' },
  },
  {
    method: 'get',
    path: '/api/v1/clearance/reports',
    summary: 'List the clearance archive',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/reports/{reportId}',
    summary: 'Get an archived clearance report',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/reports/{reportId}/pdf',
    summary: 'Download a clearance PDF',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/reports/{reportId}/xlsx',
    summary: 'Download a clearance workbook',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/reports/{reportId}/csv',
    summary: 'Download clearance CSV data',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'get',
    path: '/api/v1/clearance/reports/{reportId}/print',
    summary: 'Open a printable clearance PDF',
    tag: 'Clearance',
    secured: true,
  },
  {
    method: 'patch',
    path: '/api/v1/clearance/reports/{reportId}/revoke',
    summary: 'Revoke a clearance report',
    tag: 'Clearance',
    secured: true,
    requestExample: { reason: 'Record superseded after an attendance correction' },
  },
  {
    method: 'post',
    path: '/api/v1/clearance/reports/{reportId}/share',
    summary: 'Record and return a clearance share link',
    tag: 'Clearance',
    secured: true,
  },
];

const parameterPattern = /\{([^}]+)\}/g;
const pathParameters = (path: string) =>
  Array.from(path.matchAll(parameterPattern), ([, name]) => ({
    name,
    in: 'path',
    required: true,
    description: `The ${name} identifier.`,
    schema: { type: 'string' },
  }));

const successResponse = {
  description: 'Request completed successfully.',
  content: {
    'application/json': {
      schema: { $ref: '#/components/schemas/ApiResponse' },
      example: {
        success: true,
        message: 'Request completed successfully.',
        data: {},
        timestamp: '2026-07-31T12:00:00.000Z',
      },
    },
  },
};

const paths = routes.reduce<Record<string, Record<string, unknown>>>((document, route) => {
  const operation: Record<string, unknown> = {
    tags: [route.tag],
    summary: route.summary,
    description: `${route.summary}. Responses use the standard Attendity API envelope and tenant-scoped authorisation where indicated.`,
    operationId: `${route.method}${route.path.replace(/[^a-zA-Z0-9]+(.)/g, (_match, character: string) => character.toUpperCase())}`,
    parameters: pathParameters(route.path),
    responses: {
      '200': successResponse,
      '400': { $ref: '#/components/responses/BadRequest' },
      '401': { $ref: '#/components/responses/Unauthorised' },
      '403': { $ref: '#/components/responses/Forbidden' },
      '429': { $ref: '#/components/responses/RateLimited' },
    },
  };
  if (route.secured) operation.security = [{ bearerAuth: [] }];
  if (route.requestExample)
    operation.requestBody = {
      required: true,
      content: {
        'application/json': {
          schema: { type: 'object', additionalProperties: true },
          example: route.requestExample,
        },
      },
    };
  document[route.path] = { ...document[route.path], [route.method]: operation };
  return document;
}, {});

export const openApiDocument = {
  openapi: '3.1.0',
  info: {
    title: 'Attendity API',
    version: '1.0.0',
    description:
      'Production API for multi-tenant post-secondary attendance, analytics, notifications, and examination clearance.',
    contact: { name: 'Attendity engineering', email: 'engineering@attendity.ng' },
    license: { name: 'MIT', identifier: 'MIT' },
  },
  servers: [{ url: environment.API_PUBLIC_URL, description: environment.NODE_ENV }],
  tags: [...new Set(routes.map((route) => route.tag))].map((name) => ({ name })),
  paths,
  components: {
    securitySchemes: {
      bearerAuth: { type: 'http', scheme: 'bearer', bearerFormat: 'JWT' },
    },
    schemas: {
      ApiResponse: {
        type: 'object',
        required: ['success', 'message', 'data', 'timestamp'],
        properties: {
          success: { type: 'boolean' },
          message: { type: 'string' },
          data: {},
          timestamp: { type: 'string', format: 'date-time' },
          errors: { type: 'object', additionalProperties: true },
        },
      },
      ErrorResponse: {
        allOf: [
          { $ref: '#/components/schemas/ApiResponse' },
          { type: 'object', properties: { success: { const: false }, data: { type: 'null' } } },
        ],
      },
    },
    responses: Object.fromEntries(
      [
        ['BadRequest', 'The request is invalid.'],
        ['Unauthorised', 'Authentication is required.'],
        ['Forbidden', 'The actor lacks the required permission.'],
        ['RateLimited', 'The request limit has been exceeded.'],
      ].map(([name, description]) => [
        name,
        {
          description,
          content: {
            'application/json': { schema: { $ref: '#/components/schemas/ErrorResponse' } },
          },
        },
      ]),
    ),
  },
} as const;
