import PDFDocument from 'pdfkit';
import QRCode from 'qrcode';

const FOREST = '#14532D';
const NAVY = '#0B2638';
const GOLD = '#D4AA48';
const INK = '#17201A';
const MUTED = '#5F6F65';

export interface StaticAttendanceQrPdfInput {
  readonly checkInWindow: string;
  readonly course: string;
  readonly institution: string;
  readonly lecturer: string;
  readonly qrToken: string;
  readonly reportId: string;
  readonly logo?: { readonly buffer: Buffer; readonly mimeType: 'image/png' | 'image/jpeg' };
}

export async function renderStaticAttendanceQrPdf(
  input: StaticAttendanceQrPdfInput,
): Promise<Buffer> {
  const qr = await QRCode.toBuffer(input.qrToken, {
    type: 'png',
    width: 720,
    margin: 2,
    errorCorrectionLevel: 'H',
    color: { dark: NAVY, light: '#FFFFFF' },
  });

  return new Promise((resolve, reject) => {
    const document = new PDFDocument({
      size: 'A4',
      margins: { top: 44, right: 44, bottom: 44, left: 44 },
      info: {
        Title: `Static Attendance QR ${input.reportId}`,
        Author: input.institution,
        Subject: 'Attendity static class attendance check-in',
        Keywords: 'Attendity, attendance, static QR, class check-in',
      },
    });
    const chunks: Buffer[] = [];
    document.on('data', (chunk: Buffer) => chunks.push(chunk));
    document.on('error', reject);
    document.on('end', () => resolve(Buffer.concat(chunks)));

    const width = document.page.width;
    const contentWidth = width - 88;
    document.rect(0, 0, width, 118).fill(NAVY);
    if (input.logo) {
      try {
        document.image(input.logo.buffer, width - 104, 28, {
          fit: [60, 60],
          align: 'center',
          valign: 'center',
        });
      } catch {
        // The institution name remains the authoritative branding fallback.
      }
    }
    document
      .fillColor('#FFFFFF')
      .font('Helvetica-Bold')
      .fontSize(23)
      .text('ATTENDITY', 44, 32, { width: contentWidth - 72 });
    document
      .fillColor(GOLD)
      .font('Helvetica-Bold')
      .fontSize(10)
      .text('STATIC CLASS ATTENDANCE QR', 44, 68, { characterSpacing: 1.1 });
    document
      .fillColor('#DCE8E2')
      .font('Helvetica')
      .fontSize(9)
      .text(input.institution, 44, 89, { width: contentWidth });

    document
      .fillColor(INK)
      .font('Helvetica-Bold')
      .fontSize(18)
      .text(input.course, 44, 145, { width: contentWidth, align: 'center' });
    document
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(10)
      .text(`Lecturer: ${input.lecturer}`, 44, 177, { width: contentWidth, align: 'center' });

    document.roundedRect(152, 211, 291, 291, 18).fillAndStroke('#FFFFFF', '#C7D8CF');
    document.image(qr, 169, 228, { fit: [257, 257], align: 'center', valign: 'center' });

    document.roundedRect(78, 530, width - 156, 82, 14).fill('#EAF5EF');
    document
      .fillColor(FOREST)
      .font('Helvetica-Bold')
      .fontSize(10)
      .text('CHECK-IN WINDOW', 94, 548, { width: width - 188, align: 'center' });
    document
      .fillColor(INK)
      .font('Helvetica-Bold')
      .fontSize(13)
      .text(input.checkInWindow, 94, 569, { width: width - 188, align: 'center' });
    document
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(8.5)
      .text('This QR expires automatically when the check-in window closes.', 94, 592, {
        width: width - 188,
        align: 'center',
      });

    document
      .fillColor(INK)
      .font('Helvetica-Bold')
      .fontSize(10)
      .text('Student instructions', 78, 648);
    document
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(9)
      .text(
        'Sign in to Attendity, open the attendance scanner, and scan this code during the stated window. Registration, duplicate, GPS, and face checks remain active when configured.',
        78,
        668,
        { width: width - 156, lineGap: 3, align: 'center' },
      );

    document
      .moveTo(44, 744)
      .lineTo(width - 44, 744)
      .strokeColor('#D7E1DA')
      .stroke();
    document
      .fillColor(MUTED)
      .font('Helvetica')
      .fontSize(7.5)
      .text(`Document ID: ${input.reportId}`, 44, 758, { width: contentWidth, align: 'center' });
    document.text(
      'Generated by Attendity · Server validation is required for every scan.',
      44,
      775,
      {
        width: contentWidth,
        align: 'center',
      },
    );
    document.end();
  });
}
